name: publish

on:
  push:
    branches: [ ci-publish-job ]

jobs:
  publish-osx:
    runs-on: ubuntu-latest

    steps:
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.1.1-setup #${{ github.ref }}
        release_name: Tippy ${{ github.ref }}
        body: |
          TODO
          - TODO
          - TODO
        draft: true

    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Fetch ckb binaries
      run: ./tools/download-binaries.sh mac
    - name: Build
      run: dotnet build -c Release
    - name: Publish
      run: dotnet publish src/Tippy/Tippy.csproj -c Release -r osx-x64 /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true -o ./bin/publish/tippy-osx-x64
    - name: Archive files
      uses: papeloto/action-zip@v1
      with:
        files: ./bin/publish/tippy-osx-x64
        dest: tippy-osx-x64.zip
    - name: Generate checksum
      run: sha256sum tippy-osx-x64.zip > tippy-osx-x64.sha256.txt
    - name: Upload binary
      id: upload-release-binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/tippy-osx-x64.zip
        asset_name: tippy-osx-x64.zip
        asset_content_type: application/zip
    - name: Upload checksum
      id: upload-release-checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/tippy-osx-x64.sha256.txt
        asset_name: tippy-osx-x64.sha256.txt
        asset_content_type: text/plain
